disabled_rules:
  - todo
  - unused_closure_parameter
  - identifier_name
  - line_length
  - trailing_whitespace
  - function_body_length

custom_rules:
  mark_spacing:
    name: "MARK Surrounded by Blank Lines"
    regex: '// MARK:[^\n]*(\n)(?!\n)|[^\s{]\n[^\n\/]*// MARK:'
    message: "Ensure MARK comments are surrounded by a single blank line before and after"
    severity: warning
