disabled_rules:
  - todo
  - unused_closure_parameter
  - identifier_name
  - line_length
  - trailing_whitespace
  - function_body_length
  - trailing_comma
  - opening_brace # swiftformat will handle this

type_body_length:
  - 300 # warning
  - 400 # error

custom_rules:
  mark_spacing:
    name: "MARK Surrounded by Blank Lines"
    regex: '// MARK:[^\n]*(\n)(?!\n)|[^\s{]\n[^\n\/]*// MARK:'
    message: "Ensure MARK comments are surrounded by a single blank line before and after"
    severity: warning
